# Site settings
title: Tacto Haptics
header-img: img/tacto_glove.jpg
email: tactohaptics@gmail.com
copyright_name: 
description: "Tacto Haptics Description HERE"
baseurl: ""
url: "https://tactohaptics.github.io"
twitter_username: tactohaptics
github_username:  tactohaptics
facebook_username:  tactohaptics
email_username:  tactohaptics

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
